PUT http://localhost:8080/integrantes/42
Content-Type: application/json

{
"nome": "Matheus", "cpf": "14433777769", "data_nasc": "2021-04-17T10:48:18.584Z", "plano":"Gold","resgate_ativo":true,"desconto_farm":false,
"tel_res":"2199934666","tel_cel":"2199945678","email":"testealt@gmail.com"
}